global using Microsoft.Extensions.Configuration;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using RazorLight;
global using System.Diagnostics;
global using System.Xml.Linq;
global using System.Xml;
global using TtrxToHtml.Console;
global using TtrxToHtml.Console.Models;